CREATE TABLE display_data.datapoints (
                                         session_foreign_key INTEGER,
                                         absolute_timestamp TIMESTAMP,
                                         relative_timestamp INTERVAL,
                                         lap INTEGER,
                                         gps_position POINT,
                                         gps_speed REAL,
                                         sas REAL,
                                         apps REAL,
                                         brake_pressure REAL,
                                         wheel_speed REAL[],
                                         tyre_pressure REAL[],
                                         tyre_temp REAL[],
                                         tyre_temp_surface REAL[],
                                         suspension_travel REAL[],
                                         ssc_err BOOLEAN,
                                         imd_err BOOLEAN,
                                         inv_err BOOLEAN,
                                         bat_err BOOLEAN,
                                         FOREIGN KEY (session_foreign_key) REFERENCES Datasets(identifier),
                                         PRIMARY KEY (session_foreign_key, relative_timestamp)
);